server:
  port: 8080

spring:
  datasource:
    name: sample_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sample_db
    username: root
    password: vamsi
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update